const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 199.99,
    category: "Electronics",
    brand: "Sony",
    createdAt: "Jul 04, 2024",
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    price: 149,
    category: "Electronics",
    brand: "Razer",
    createdAt: "Jul 04, 2024",
  },
  {
    id: 3,
    name: "iPhone 9",
    price: 549,
    category: "smartphones",
    brand: "Apple",
    createdAt: "Jul 04, 2024",
  },
  {
    id: 4,
    name: "Samsung Universe 9",
    price: 1249,
    category: "smartphones",
    brand: "Samsung",
    createdAt: "Jul 04, 2024",
  },
  {
    id: 5,
    name: "Samsung Galaxy Book",
    price: 1499,
    category: "laptops",
    brand: "Samsung",
    createdAt: "Jul 04, 2024",
  },
  {
    id: 6,
    name: "Microsoft Surface Laptop 4",
    price: 1499,
    category: "laptops",
    brand: "Microsoft Surface",
    createdAt: "Jul 04, 2024",
  },
  {
    id: 7,
    name: "Vostro 15",
    price: 1599,
    category: "laptops",
    brand: "Dell",
    createdAt: "Jul 04, 2024",
  },
  {
    id: 8,
    name: "Infinix INBOOK",
    price: 1099,
    category: "laptops",
    brand: "Infinix",
    createdAt: "Jul 04, 2024",
  },
];

export default products;
